name: Stage CI/CD

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PNPM="$PNPM:/usr/bin/pnpm"
            cd /var/www/healthlinker-backend-stage
            git switch stage
            git pull
            pnpm install
            pnpm migrate:prod
            pnpm build
            pm2 restart healthlinker-backend-stage --update-env
